### PR TITLE
Fix Error on install: -bash: -e: command not found

### LINKED ISSUE #5: Error on install: -bash: -e: command not found
I have updated to the latest version of the completions. But i get an error when i run this command:

```bash 
source sfdx.bash
```

The error:
```bash
-bash: -e: command not found
```

I am using Mac OS 10.14.5.

### PR DESCRIPTION
**Pull request by thvd**
Fixes #5

Before merging though, i do think it's good to know why in the first place the `-e` option was added. So we are sure there is nothing breaking with this fix.

### CODE REVIEW

**Comment by wadewegner** [comment]
Thanks @thvd. @rrmehta2 can you take a look?

**Comment by mloh** [comment]
In commit b5f0a380 the echo command added the -e argument to `generate.sh`. The next commit only updates `sfdx.bash`, which was probably the result of running `generate.sh` and not testing output.

The problem is that when running `generate.sh` with something other than the correct version of bash, if the resolved `echo` command doesn't recognize the `-e` arg, then the running shell will just echo "-e".

So when `sfdx.bash` was last generated and committed, it was probably done with something other than bash4. Given the comment here: https://github.com/wadewegner/salesforce-cli-bash-completion/pull/4 I'm wondering if bash3 was installed for testing and not removed.

**Review by yogeshdixit41 — APPROVED** [review]

**Comment by yogeshdixit41** [comment]
I think @mloh is correct. -e was added to generated sfdx as a result of -e flag that was added in . generate.sh. Its weird but for some reason it looks like -e is not required (and adds extra -e character) for interpretation of escape characters when it comes to generating sfdx from generate.sh with echo. So i don't think merging this will break anything. But as of now current master branch is failing because of the extra '-e' character and won't work whatsoever until you remove it from the generated sfdx script.

**Comment by umeditor** [comment]
FWIW, this allowed me to install and run the code.

**Review by alexrindone — APPROVED** [review]
This worked.

**Comment by thvd** [comment]
@wadewegner looks like this pr helps people run the code. Is there anything needed in order to merge this one?

**Comment by wadewegner** [comment]
Sorry all. This should have been fixed a long time ago. I just pushed an update to `generate.sh` and this resolved the problem.

**Pull request closed without merging**
